
package Vista;


public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        configurarPlaceholders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setText("LOGIN");

        jTextField2.setText("Nombre de Usuario");

        txtContrasena.setText("Contraseña");

        btnEntrar.setText("Entrar");

        btnRegistrarse.setText("Registrarse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Configura los placeholders de los campos
private void configurarPlaceholders() {

    // Placeholder para jTextField2 (campo de usuario)
    jTextField2.setForeground(java.awt.Color.GRAY);
    jTextField2.setText("Nombre de Usuario");
    jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent e) {
            if (jTextField2.getText().equals("Nombre de Usuario")) {
                jTextField2.setText("");
                jTextField2.setForeground(java.awt.Color.BLACK);
            }
        }
        public void focusLost(java.awt.event.FocusEvent e) {
            if (jTextField2.getText().isEmpty()) {
                jTextField2.setForeground(java.awt.Color.GRAY);
                jTextField2.setText("Nombre de Usuario");
            }
        }
    });

    // Placeholder para txtContrasena (campo de contraseña oculta)
    txtContrasena.setForeground(java.awt.Color.GRAY);
    txtContrasena.setEchoChar((char) 0);
    txtContrasena.setText("Contraseña");
    txtContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent e) {
            if (String.valueOf(txtContrasena.getPassword()).equals("Contraseña")) {
                txtContrasena.setText("");
                txtContrasena.setForeground(java.awt.Color.BLACK);
                txtContrasena.setEchoChar('●');
            }
        }
        public void focusLost(java.awt.event.FocusEvent e) {
            if (String.valueOf(txtContrasena.getPassword()).isEmpty()) {
                txtContrasena.setForeground(java.awt.Color.GRAY);
                txtContrasena.setEchoChar((char) 0);
                txtContrasena.setText("Contraseña");
            }
        }
    });
}

// Retorna el usuario ingresado, excluyendo el placeholder
public String getUsuario() {
    String texto = jTextField2.getText();
    return texto.equals("Nombre de Usuario") ? "" : texto;
}

// Retorna la contraseña ingresada, excluyendo el placeholder
public String getContrasena() {
    String pass = new String(txtContrasena.getPassword());
    return pass.equals("Contraseña") ? "" : pass;
}

// Retorna el botón Entrar para asignarle acción desde el controlador
public javax.swing.JButton getBtnEntrar() { return btnEntrar; }

// Retorna el botón Registrarse para asignarle acción desde el controlador
public javax.swing.JButton getBtnRegistrarse() { return btnRegistrarse; }

// Limpia ambos campos y restaura los placeholders
public void limpiarCampos() {
    jTextField2.setForeground(java.awt.Color.GRAY);
    jTextField2.setText("Nombre de Usuario");
    txtContrasena.setForeground(java.awt.Color.GRAY);
    txtContrasena.setEchoChar((char) 0);
    txtContrasena.setText("Contraseña");
}

// Muestra un mensaje de error en ventana emergente
public void mostrarError(String mensaje) {
    javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error", 
        javax.swing.JOptionPane.ERROR_MESSAGE);
}

// Muestra un mensaje de éxito en ventana emergente
public void mostrarExito(String mensaje) {
    javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Éxito", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
}

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
    // Manejado por el controlador
}

private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {
    // Manejado por el controlador
}

private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {
    // Manejado por el controlador
}

private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {
    // Manejado por el controlador
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables
}


