
package Vista;

// Ventana principal que muestra el listado de usuarios registrados
public class PrincipalFrame extends javax.swing.JFrame {

    // Logger para registrar errores del sistema
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalFrame.class.getName());

    // Constructor: inicializa componentes, tabla y estilos visuales
    public PrincipalFrame() {
        initComponents();
        configurarTabla();
        aplicarEstilos(); // Aplica estilos visuales
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(100, 35));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setText("Clientes Registrados");

        btnNuevo.setText("Nuevo");
        btnNuevo.setMaximumSize(new java.awt.Dimension(100, 35));

        btnEliminar.setText("Eliminar");
        btnEliminar.setMaximumSize(new java.awt.Dimension(100, 35));

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setMaximumSize(new java.awt.Dimension(100, 35));

        btnActualizar.setText("Actualizar");
        btnActualizar.setMaximumSize(new java.awt.Dimension(100, 35));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Telefono", "Correo"
            }
        ));
        jScrollPane2.setViewportView(tblUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  // Aplica todos los estilos visuales a los componentes de la ventana
    private void aplicarEstilos() {

        // ─── FONDO DE LA VENTANA ──────────────────────────────────
        // Color azul muy claro consistente con Login y Registro
        getContentPane().setBackground(new java.awt.Color(235, 243, 255));

        // ─── TÍTULO ───────────────────────────────────────────────
        // Fuente grande en negrita con color azul corporativo
        lblTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));
        lblTitulo.setForeground(new java.awt.Color(26, 82, 160));

        // ─── TABLA DE USUARIOS ────────────────────────────────────
        // Encabezado de la tabla con fondo azul y texto blanco
        tblUsuarios.getTableHeader().setBackground(new java.awt.Color(26, 82, 160));
        tblUsuarios.getTableHeader().setForeground(java.awt.Color.WHITE);
        tblUsuarios.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        // Filas con fuente limpia y altura mayor para mejor legibilidad
        tblUsuarios.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        tblUsuarios.setRowHeight(28);
        // Color de selección de fila en azul claro
        tblUsuarios.setSelectionBackground(new java.awt.Color(173, 214, 255));
        tblUsuarios.setSelectionForeground(java.awt.Color.BLACK);
        // Líneas de la cuadrícula en azul muy claro
        tblUsuarios.setGridColor(new java.awt.Color(200, 220, 245));
        tblUsuarios.setBackground(java.awt.Color.WHITE);

        // ─── BOTÓN NUEVO ──────────────────────────────────────────
        // Azul corporativo — acción principal para agregar usuarios
        btnNuevo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        btnNuevo.setBackground(new java.awt.Color(26, 82, 160));
        btnNuevo.setForeground(java.awt.Color.WHITE);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setFocusPainted(false);
        btnNuevo.setOpaque(true);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // ─── BOTÓN ACTUALIZAR ─────────────────────────────────────
        // Azul medio — acción de modificación
        btnActualizar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        btnActualizar.setBackground(new java.awt.Color(52, 120, 210));
        btnActualizar.setForeground(java.awt.Color.WHITE);
        btnActualizar.setBorderPainted(false);
        btnActualizar.setFocusPainted(false);
        btnActualizar.setOpaque(true);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // ─── BOTÓN ELIMINAR ───────────────────────────────────────
        // Rojo — acción de peligro/eliminación
        btnEliminar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        btnEliminar.setBackground(new java.awt.Color(200, 50, 50));
        btnEliminar.setForeground(java.awt.Color.WHITE);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setOpaque(true);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // ─── BOTÓN CERRAR SESIÓN ──────────────────────────────────
        // Gris — acción de salida/cancelar sesión
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        btnCerrarSesion.setBackground(new java.awt.Color(108, 117, 125));
        btnCerrarSesion.setForeground(java.awt.Color.WHITE);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setOpaque(true);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    // Configura la tabla para que no sea editable directamente
    private void configurarTabla() {
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Nombre", "Apellido", "Teléfono", "Correo", "Usuario"}
        ) {
            // La tabla no es editable directamente, se edita desde el controlador
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        // Permite seleccionar solo una fila a la vez
        tblUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    // Retorna el modelo de la tabla para manipularlo desde el controlador
    public javax.swing.table.DefaultTableModel getModeloTabla() {
        return (javax.swing.table.DefaultTableModel) tblUsuarios.getModel();
    }

    // Retorna la tabla para leer la fila seleccionada desde el controlador
    public javax.swing.JTable getTblUsuarios() { return tblUsuarios; }

    // Retorna el índice de la fila seleccionada en la tabla
    public int getFilaSeleccionada() {
        return tblUsuarios.getSelectedRow();
    }

    // Retorna el botón Nuevo para asignarle acción desde el controlador
    public javax.swing.JButton getBtnNuevo() { return btnNuevo; }

    // Retorna el botón Actualizar para asignarle acción desde el controlador
    public javax.swing.JButton getBtnActualizar() { return btnActualizar; }

    // Retorna el botón Eliminar para asignarle acción desde el controlador
    public javax.swing.JButton getBtnEliminar() { return btnEliminar; }

    // Retorna el botón Cerrar Sesión para asignarle acción desde el controlador
    public javax.swing.JButton getBtnCerrarSesion() { return btnCerrarSesion; }

    // Muestra un mensaje de error en ventana emergente
    public void mostrarError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    // Muestra un mensaje de éxito en ventana emergente
    public void mostrarExito(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    // Muestra un diálogo de confirmación y retorna true si el usuario acepta
    public boolean confirmar(String mensaje) {
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, mensaje,
            "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
        return respuesta == javax.swing.JOptionPane.YES_OPTION;
    }

    // Método principal para pruebas — en producción se usa MainTarea4.java
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new PrincipalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
